name: CI/CD Docker Swarm ACR

on:
  push:
    branches:
      - prd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.AZURE_VM_SSH_KEY }}

      - name: Login to Azure Container Registry
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login olivesoft.azurecr.io -u olivesoft --password-stdin
      - name: Build Docker image
        run: |
          docker build -t olivesoft.azurecr.io/open-webui-custom:latest .
      - name: Push Docker image to ACR
        run: |
          docker push olivesoft.azurecr.io/open-webui-custom:latest
      - name: Deploy to Swarm VM
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@40.66.43.12 "
            docker login olivesoft.azurecr.io -u olivesoft -p ${{ secrets.ACR_PASSWORD }}
            docker pull olivesoft.azurecr.io/open-webui-custom:latest
            docker service update -d --with-registry-auth --image olivesoft.azurecr.io/open-webui-custom:latest platform_webapp
          "
